import CyclicTactic.SizeChange
import CyclicTactic.Measure
import CyclicTactic.ProofTree
import CyclicTactic.InductionOrder

/-!
# Paper-style reset annotation (Grotenhuis-Otten, "An Abstract Cyclic
Proof System", §5; cf. Wehr 2025 PhD thesis §3.3-3.4 "stack-controlled /
reset proofs")

For a cyclic proof that passes SCT, this module computes a *reset
annotation*: for each back-edge, a "progressing name" — i.e. an argument
position that strictly descends along the closure cycle through that
back-edge — together with a textual witness (the closure idempotent)
explaining why. The output also includes a *global induction order* on
positions, used to drive both the synthesised termination measure and
per-back-edge `decreasing_by`-style commentary in the emitted def.

## Correspondence with the paper

The paper's Stack/Name annotation (Definition 5.1) and reset proof
(Theorem 5.2) are formulated for proofs whose names can be introduced
and renamed at each rule. Our cyclic-proof model has flat arity — the
"names" are just the root judgment's argument positions, threaded
unchanged through the proof. In this restricted setting, the paper's
construction collapses to:

  * `Stack(n_k)_j ≡ ⟨j⟩` (each position is its own singleton stack),
  * `Name(n_k) ≡ ⟨0, 1, …, arity-1⟩` at every node,
  * `var(n_k, j) ≡` the j-th argument of the root predicate.

The substantive content — choosing `prog(n_t) ∈ Reset(n_b)` per
back-edge and verifying its preservation — is what this module
implements. We do **not** restructure the proof tree per Proposition 5.8;
that is unnecessary in our flat setting because Lean's `WellFounded.fix`
provides a single uniform top-level IH, abstracting over the >-ind_x
nesting order the paper makes explicit at each sprout.

What this module DOES give over the bare measure synthesiser:

  1. **Per-back-edge attribution.** A measure tells you "the proof
     descends in lex (a₀, a₁)"; an annotation tells you "back-edge B0
     descends on a₀, B1 descends on a₁, both via the same closure
     idempotent." That distinction matters when reading a proof, when
     debugging an SCT pass that didn't produce the measure you expected,
     and when emitting per-recursive-call provenance comments.
  2. **A separate, paper-faithful entry point for analysis.** Even if
     the rest of the pipeline switched away from `WellFounded.fix` (e.g.
     to a more explicit `Nat.rec` style emission), the annotation pass
     would remain the right interface to the SCT closure.
-/

namespace CyclicTactic.Annotation

open CyclicTactic.Proof

/-- Per-back-edge annotation: the chosen progressing position plus all
    candidates from the cycle's closure-idempotent witness. -/
structure BackEdgeAnnot where
  /-- The back-edge's label in the proof tree. Auto-generated by the DSL
      walker (e.g. `_B0`, `_B1`); used to key per-call commentary. -/
  label : String
  /-- The chosen progressing name — a position with a strict self-loop
      in the closure idempotent reachable from this back-edge. Ties are
      broken by the global induction order: earlier-priority positions
      win, so per-back-edge progs are mutually consistent. -/
  progPos : Nat
  /-- All positions with strict self-loops in this back-edge's closure
      idempotent. `progPos` is one of these. The full list is surfaced
      in diagnostics so the user sees the SCT witness's resolution
      latitude. -/
  candidates : List Nat
  /-- Compact rendering of the closure idempotent for diagnostics. -/
  cycleWitness : String
  deriving Repr, Inhabited

/-- Full reset annotation of a cyclic proof. -/
structure ProofAnnot where
  arity : Nat
  /-- Per-back-edge prog assignments, in extraction order. -/
  backEdges : List BackEdgeAnnot
  /-- Global induction order: positions in lex priority, outer first.
      A subset of `[0..arity)` containing every back-edge's `progPos`
      whenever the underlying SCT permits a lex measure. -/
  inductionOrder : List Nat
  deriving Repr, Inhabited

/-- Iterate `g` under self-composition until it becomes idempotent (or
    `fuel` runs out). When SCT validates and `g` itself participates in
    a single-back-edge cycle, the iteration terminates at `g^k` for some
    `k` ≤ |closure(g)|. Returns the last iterate if fuel runs out — the
    annotation's `candidates` list will then be approximate but the
    overall pipeline still elaborates (the synthesised `Measure` is the
    actual termination certificate). -/
partial def iterateToIdempotent (g : SCGraph) (fuel : Nat) : SCGraph :=
  go g fuel
where
  go (cur : SCGraph) (k : Nat) : SCGraph :=
    if cur.isIdempotent then cur
    else
      match k with
      | 0     => cur
      | n + 1 => go ((cur.comp g).canon) n

/-- Look up the per-back-edge annotation by label. -/
def ProofAnnot.find? (a : ProofAnnot) (label : String) : Option BackEdgeAnnot :=
  a.backEdges.find? (·.label == label)

/-- Variable names corresponding to the annotation's induction order
    (positions → variable names), looked up via `varSorts` mapping. -/
def ProofAnnot.varOrder (a : ProofAnnot)
    (varSorts : List (String × β)) : List String :=
  a.inductionOrder.filterMap fun i => varSorts[i]?.map (·.1)

/-- Does the proof tree's case-split nesting match the induction order
    as a prefix? Every path from the root encounters the variables of
    `order` outermost-first; paths that terminate early (in a leaf or
    back-edge) are accepted. Paths whose case-split disagrees with the
    expected variable at any level are rejected.

    Original — this is a Lean-emission-feasibility check, not from the
    paper. The paper's reset annotation guarantees the *existence* of a
    valid lex induction over names; we additionally check that the
    user's case-split nesting *agrees with* that order, because Lean's
    nested `induction var generalizing rest` only binds the right IH
    when the surface syntax matches. When this returns `false`, the
    dispatcher invokes `CyclicTactic.Reorganize` to reshape the tree. -/
partial def treeMatchesOrder : List String → CyclicTactic.Proof.ProofTree → Bool
  | [], _                                          => true
  | _, .leaf _ _ _ _                               => true
  | _, .identity _ _                               => true
  | _, .back _ _ _ _ _                             => true
  | order, .node _ _ _ cs                          => cs.all (treeMatchesOrder order)
  | order, .haveStep _ _ _ _ _ cont                => treeMatchesOrder order cont
  | order, .existsStep _ _ _ cont                  => treeMatchesOrder order cont
  | v :: rest, .caseSplit _ _ v' cs                =>
    if v' == v then cs.all (fun (_, sub) => treeMatchesOrder rest sub)
    else false

/-- Can the structural emitter (nested `induction` per variable in
    `inductionOrder`) discharge every back-edge in this proof?

    Two conditions:

    1. **SCG check.** Every input back-edge SCG `lex-validates` against
       the order — for each back-edge there is a position `p` in the
       order with strict self-loop in the back-edge's input graph, and
       every position before `p` has at least a non-strict self-loop.
    2. **Tree-shape check.** The user's case-split nesting matches the
       induction order outermost-first (`treeMatchesOrder`). Without
       this, the IH bound by `induction var generalizing …` doesn't
       align with what the back-edges need — a back-edge descending on
       `v_p` expects an enclosing `induction v_p` ancestor; if the
       tree's outer is a *different* variable, the IH lookup fails.

    When `false` the dispatcher tries reorganisation (`CyclicTactic.Reorganize`)
    to permute the case-splits into the right order, then re-checks. If
    reorganisation can't fix it (sum/swap cases, non-uniform trees,
    multi-recursive constructors), falls through to WF emission. -/
def ProofAnnot.canStructural (a : ProofAnnot)
    (labeledGraphs : List (String × SCGraph))
    (proofTree : CyclicTactic.Proof.ProofTree)
    (varSorts : List (String × β)) : Bool :=
  ¬ a.inductionOrder.isEmpty
    && labeledGraphs.all (fun (_, g) => lexValidates a.inductionOrder g)
    && treeMatchesOrder (a.varOrder varSorts) proofTree

/-- Compute the reset annotation. The `(label, scg)` pairs must
    correspond one-to-one with the proof's back-edges, in extraction
    order — pass the output of `extractTraceSCGsLabeled` directly.

    When `tree?` is supplied, the order-finding uses Wehr Theorem 3.2.4
    (`CyclicTactic.InductionOrder.findInductionOrder`) — the paper-faithful
    SCC-based construction. When the tree isn't available or the
    algorithm fails (e.g. swap/sum-style proofs with no lex measure),
    falls back to the closure-witness greedy and brute-force schemas.

    Returns `Except String` so SCT failures can be surfaced with a
    diagnostic prefix; callers that have already SCT-validated may
    treat any error as an internal-consistency violation. -/
def annotate (labeled : List (String × SCGraph)) (arity : Nat)
    (tree? : Option CyclicTactic.Proof.ProofTree := none) (fuel : Nat := 100)
    : Except String ProofAnnot := do
  let gs := labeled.map (·.2)
  unless SCGraph.checkMultiSCT gs fuel do
    throw "annotate: SCT failed (some closure idempotent has no strict self-loop)"
  -- Try Wehr 3.2.4 first when we have the tree. The algorithm gives
  -- both the global induction order *and* the per-bud progressing
  -- assignment in one pass, so we capture its assignment when it
  -- succeeds and use it directly for `BackEdgeAnnot.progPos`.
  let wehrAssignment? : Option (List (String × Nat)) :=
    tree?.bind fun t =>
      CyclicTactic.InductionOrder.findInductionOrder t labeled arity
  -- Global induction order: Wehr → closure-witness greedy → brute-force
  -- permutation → numeric. Numeric is the last resort for sum cases.
  let order : List Nat :=
    match wehrAssignment? with
    | some asg => CyclicTactic.InductionOrder.lexOrderFromAssignment asg
    | none =>
      match synthLexGreedy gs arity fuel with
      | some o => o
      | none =>
        match synthLexOrder gs arity with
        | some o => o
        | none   => List.range arity
  -- Per back-edge: prefer Wehr's per-bud assignment when available;
  -- otherwise compute from the closure idempotent reachable from the
  -- back-edge, picking the first position in the global order that
  -- has a strict self-loop in the idempotent.
  let backAnnots := labeled.map fun (lbl, g) =>
    let idem := iterateToIdempotent g fuel
    let strictPositions := idem.strictSelfLoopPositions arity
    let chosen :=
      match wehrAssignment?.bind (·.lookup lbl) with
      | some p => p
      | none =>
        match order.find? (fun p => strictPositions.elem p) with
        | some p => p
        | none   => strictPositions.head?.getD 0
    { label := lbl
      progPos := chosen
      candidates := strictPositions
      cycleWitness := toString idem }
  return { arity := arity
           backEdges := backAnnots
           inductionOrder := order }

/-- Render the annotation as a multi-line diagnostic string. -/
def render (a : ProofAnnot) : String :=
  let orderStr :=
    if a.inductionOrder.isEmpty then "(none)"
    else String.intercalate " ≻ " (a.inductionOrder.map (fun i => s!"a{i}"))
  let beStr :=
    if a.backEdges.isEmpty then "  (no back-edges)"
    else String.intercalate "\n" (a.backEdges.map fun be =>
      let cands :=
        if be.candidates.isEmpty then "∅"
        else "{" ++ String.intercalate ", " (be.candidates.map toString) ++ "}"
      "  " ++ be.label ++ ": prog = a" ++ toString be.progPos
        ++ "; candidates = " ++ cands
        ++ "; cycle = " ++ be.cycleWitness)
  "induction order: " ++ orderStr ++ "\nback-edges:\n" ++ beStr

/-! ### Diagnostic checks -/

-- Ackermann-shape: lex (m, n), one back-edge with strict on slot 0
#eval annotate
  [("_B0", ⟨2, 2, [⟨0, 0, .strict⟩]⟩),
   ("_B1", ⟨2, 2, [⟨0, 0, .nonstrict⟩, ⟨1, 1, .strict⟩]⟩)] 2
  |>.toOption.map render
-- expected:
--   induction order: a0 ≻ a1
--   _B0: prog = a0; ...
--   _B1: prog = a0 (since strict at 0 in idempotent of B1 is also true via closure)

-- Single back-edge, single position
#eval annotate
  [("back0", ⟨1, 1, [⟨0, 0, .strict⟩]⟩)] 1
  |>.toOption.map render

end CyclicTactic.Annotation
