import Cyclic.SizeChange
import Cyclic.Measure
import Cyclic.ProofTree

/-!
# Paper-style reset annotation (Grotenhuis-Otten, Section 5)

For a cyclic proof that passes SCT, this module computes a *reset
annotation*: for each back-edge, a "progressing name" — i.e. an argument
position that strictly descends along the closure cycle through that
back-edge — together with a textual witness (the closure idempotent)
explaining why. The output also includes a *global induction order* on
positions, used to drive both the synthesised termination measure and
per-back-edge `decreasing_by`-style commentary in the emitted def.

## Correspondence with the paper

The paper's Stack/Name annotation (Definition 5.1) and reset proof
(Theorem 5.2) are formulated for proofs whose names can be introduced
and renamed at each rule. Our cyclic-proof model has flat arity — the
"names" are just the root judgment's argument positions, threaded
unchanged through the proof. In this restricted setting, the paper's
construction collapses to:

  * `Stack(n_k)_j ≡ ⟨j⟩` (each position is its own singleton stack),
  * `Name(n_k) ≡ ⟨0, 1, …, arity-1⟩` at every node,
  * `var(n_k, j) ≡` the j-th argument of the root predicate.

The substantive content — choosing `prog(n_t) ∈ Reset(n_b)` per
back-edge and verifying its preservation — is what this module
implements. We do **not** restructure the proof tree per Proposition 5.8;
that is unnecessary in our flat setting because Lean's `WellFounded.fix`
provides a single uniform top-level IH, abstracting over the >-ind_x
nesting order the paper makes explicit at each sprout.

What this module DOES give over the bare measure synthesiser:

  1. **Per-back-edge attribution.** A measure tells you "the proof
     descends in lex (a₀, a₁)"; an annotation tells you "back-edge B0
     descends on a₀, B1 descends on a₁, both via the same closure
     idempotent." That distinction matters when reading a proof, when
     debugging an SCT pass that didn't produce the measure you expected,
     and when emitting per-recursive-call provenance comments.
  2. **A separate, paper-faithful entry point for analysis.** Even if
     the rest of the pipeline switched away from `WellFounded.fix` (e.g.
     to a more explicit `Nat.rec` style emission), the annotation pass
     would remain the right interface to the SCT closure.
-/

namespace Cyclic.Annotation

open Cyclic.Proof

/-- Per-back-edge annotation: the chosen progressing position plus all
    candidates from the cycle's closure-idempotent witness. -/
structure BackEdgeAnnot where
  /-- The back-edge's label in the proof tree. Auto-generated by the DSL
      walker (e.g. `_B0`, `_B1`); used to key per-call commentary. -/
  label : String
  /-- The chosen progressing name — a position with a strict self-loop
      in the closure idempotent reachable from this back-edge. Ties are
      broken by the global induction order: earlier-priority positions
      win, so per-back-edge progs are mutually consistent. -/
  progPos : Nat
  /-- All positions with strict self-loops in this back-edge's closure
      idempotent. `progPos` is one of these. The full list is surfaced
      in diagnostics so the user sees the SCT witness's resolution
      latitude. -/
  candidates : List Nat
  /-- Compact rendering of the closure idempotent for diagnostics. -/
  cycleWitness : String
  deriving Repr, Inhabited

/-- Full reset annotation of a cyclic proof. -/
structure ProofAnnot where
  arity : Nat
  /-- Per-back-edge prog assignments, in extraction order. -/
  backEdges : List BackEdgeAnnot
  /-- Global induction order: positions in lex priority, outer first.
      A subset of `[0..arity)` containing every back-edge's `progPos`
      whenever the underlying SCT permits a lex measure. -/
  inductionOrder : List Nat
  deriving Repr, Inhabited

/-- Iterate `g` under self-composition until it becomes idempotent (or
    `fuel` runs out). When SCT validates and `g` itself participates in
    a single-back-edge cycle, the iteration terminates at `g^k` for some
    `k` ≤ |closure(g)|. Returns the last iterate if fuel runs out — the
    annotation's `candidates` list will then be approximate but the
    overall pipeline still elaborates (the synthesised `Measure` is the
    actual termination certificate). -/
partial def iterateToIdempotent (g : SCGraph) (fuel : Nat) : SCGraph :=
  go g fuel
where
  go (cur : SCGraph) (k : Nat) : SCGraph :=
    if cur.isIdempotent then cur
    else
      match k with
      | 0     => cur
      | n + 1 => go ((cur.comp g).canon) n

/-- Look up the per-back-edge annotation by label. -/
def ProofAnnot.find? (a : ProofAnnot) (label : String) : Option BackEdgeAnnot :=
  a.backEdges.find? (·.label == label)

/-- Compute the reset annotation. The `(label, scg)` pairs must
    correspond one-to-one with the proof's back-edges, in extraction
    order — pass the output of `extractTraceSCGsLabeled` directly.

    Returns `Except String` so SCT failures can be surfaced with a
    diagnostic prefix; callers that have already SCT-validated may
    treat any error as an internal-consistency violation. -/
def annotate (labeled : List (String × SCGraph)) (arity : Nat) (fuel : Nat := 100)
    : Except String ProofAnnot := do
  let gs := labeled.map (·.2)
  unless SCGraph.checkMultiSCT gs fuel do
    throw "annotate: SCT failed (some closure idempotent has no strict self-loop)"
  -- Global induction order: prefer paper-faithful greedy (built from
  -- closure witnesses); fall back to brute-force permutation; last
  -- resort is numeric order (used when the only valid measure is sum).
  let order : List Nat :=
    match synthLexGreedy gs arity fuel with
    | some o => o
    | none =>
      match synthLexOrder gs arity with
      | some o => o
      | none   => List.range arity
  -- Per back-edge: walk to its closure idempotent, pick prog by global
  -- order (first match wins) so prog choices align across back-edges.
  let backAnnots := labeled.map fun (lbl, g) =>
    let idem := iterateToIdempotent g fuel
    let strictPositions := idem.strictSelfLoopPositions arity
    let chosen :=
      match order.find? (fun p => strictPositions.elem p) with
      | some p => p
      | none   => strictPositions.head?.getD 0
    { label := lbl
      progPos := chosen
      candidates := strictPositions
      cycleWitness := toString idem }
  return { arity := arity
           backEdges := backAnnots
           inductionOrder := order }

/-- Render the annotation as a multi-line diagnostic string. -/
def render (a : ProofAnnot) : String :=
  let orderStr :=
    if a.inductionOrder.isEmpty then "(none)"
    else String.intercalate " ≻ " (a.inductionOrder.map (fun i => s!"a{i}"))
  let beStr :=
    if a.backEdges.isEmpty then "  (no back-edges)"
    else String.intercalate "\n" (a.backEdges.map fun be =>
      let cands :=
        if be.candidates.isEmpty then "∅"
        else "{" ++ String.intercalate ", " (be.candidates.map toString) ++ "}"
      "  " ++ be.label ++ ": prog = a" ++ toString be.progPos
        ++ "; candidates = " ++ cands
        ++ "; cycle = " ++ be.cycleWitness)
  "induction order: " ++ orderStr ++ "\nback-edges:\n" ++ beStr

/-! ### Diagnostic checks -/

-- Ackermann-shape: lex (m, n), one back-edge with strict on slot 0
#eval annotate
  [("_B0", ⟨2, 2, [⟨0, 0, .strict⟩]⟩),
   ("_B1", ⟨2, 2, [⟨0, 0, .nonstrict⟩, ⟨1, 1, .strict⟩]⟩)] 2
  |>.toOption.map render
-- expected:
--   induction order: a0 ≻ a1
--   _B0: prog = a0; ...
--   _B1: prog = a0 (since strict at 0 in idempotent of B1 is also true via closure)

-- Single back-edge, single position
#eval annotate
  [("back0", ⟨1, 1, [⟨0, 0, .strict⟩]⟩)] 1
  |>.toOption.map render

end Cyclic.Annotation
